selected_scheme scheme-small
TEXDIR /home/tzh03/texlive/2026
TEXMFCONFIG /home/tzh03/.texlive2026/texmf-config
TEXMFHOME /home/tzh03/texmf
TEXMFLOCAL /home/tzh03/texlive/texmf-local
TEXMFSYSCONFIG /home/tzh03/texlive/2026/texmf-config
TEXMFSYSVAR /home/tzh03/texlive/2026/texmf-var
TEXMFVAR /home/tzh03/.texlive2026/texmf-var
binary_x86_64-linux 1
collection-basic 1
collection-latex 1
collection-latexrecommended 1
collection-fontsrecommended 1
collection-latexextra 1
collection-pictures 1
instopt_adjustpath 0
instopt_portable 0
tlpdbopt_install_docfiles 0
tlpdbopt_install_srcfiles 0
